// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApzm7NLG_-1qQ3RlfHdHUfr4OJbrXlHrE',
    appId: '1:340346390404:web:d345cd4d5e6a214f527fd1',
    messagingSenderId: '340346390404',
    projectId: 'engstory-48526',
    authDomain: 'engstory-48526.firebaseapp.com',
    storageBucket: 'engstory-48526.firebasestorage.app',
    measurementId: 'G-QB6V9667F1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw8O6VfFwdBr85oyDDq1zGIhgf2gvq09g',
    appId: '1:340346390404:android:2e10080b01c04760527fd1',
    messagingSenderId: '340346390404',
    projectId: 'engstory-48526',
    storageBucket: 'engstory-48526.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACdb6-1aRSZSWUYoHC76qQQt-8ZnODDoo',
    appId: '1:340346390404:ios:e9b0128cfc639f41527fd1',
    messagingSenderId: '340346390404',
    projectId: 'engstory-48526',
    storageBucket: 'engstory-48526.firebasestorage.app',
    iosBundleId: 'com.example.engStory',
  );
}
