import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:eng_story/models/story.dart';
import 'package:eng_story/models/story_script.dart';

/// 📌 The Three Little Pigs 스토리 더미 데이터
final Story dummyStoryThreeLittlePigs = Story(
  id: "three_little_pigs",
  title: "The Three Little Pigs",
  source: "Public Domain",
  category: "Fairy Tale",
  readTime: "5-10 min",
  updatedAt: Timestamp.now(),
);

/// 📌 The Three Little Pigs 스크립트 더미 데이터
final List<StoryScript> dummyStoryThreeLittlePigsScripts = [
  // Cycle 1 (scripts 1-4)
  StoryScript(
    id: "${dummyStoryThreeLittlePigs.title}_1",
    storyId: dummyStoryThreeLittlePigs.title,
    index: 1,
    role: "story_teller",
    text_en:
        "Once upon a time, three little pigs set out to build their own homes.",
    text_ko: "옛날 옛적에, 세 마리 아기돼지가 자기 집을 짓기 위해 모험을 시작했어요.",
    updatedAt: Timestamp.now(),
  ),
  StoryScript(
    id: "${dummyStoryThreeLittlePigs.title}_2",
    storyId: dummyStoryThreeLittlePigs.title,
    index: 2,
    role: "story_teller",
    text_en: "Each pig chose a different material: straw, sticks, and bricks.",
    text_ko: "각 아기돼지는 짚, 나뭇가지, 그리고 벽돌로 집을 짓기로 했어요.",
    updatedAt: Timestamp.now(),
  ),
  StoryScript(
    id: "${dummyStoryThreeLittlePigs.title}_3",
    storyId: dummyStoryThreeLittlePigs.title,
    index: 3,
    role: "story_teller",
    text_en: "Their dreams were as big as their ambitions.",
    text_ko: "그들의 꿈은 그들의 야망만큼이나 컸어요.",
    updatedAt: Timestamp.now(),
  ),
  StoryScript(
    id: "${dummyStoryThreeLittlePigs.title}_4",
    storyId: dummyStoryThreeLittlePigs.title,
    index: 4,
    role: "me",
    text_en: "How did they decide on their building materials?",
    text_ko: "어떻게 각기 다른 재료를 선택하게 되었을까요?",
    updatedAt: Timestamp.now(),
  ),
  // Cycle 2 (scripts 5-8)
  StoryScript(
    id: "${dummyStoryThreeLittlePigs.title}_5",
    storyId: dummyStoryThreeLittlePigs.title,
    index: 5,
    role: "story_teller",
    text_en: "The pig with straw believed in speed and ease.",
    text_ko: "짚으로 집을 짓는 돼지는 빠르고 쉽게 지을 수 있다고 믿었어요.",
    updatedAt: Timestamp.now(),
  ),
  StoryScript(
    id: "${dummyStoryThreeLittlePigs.title}_6",
    storyId: dummyStoryThreeLittlePigs.title,
    index: 6,
    role: "story_teller",
    text_en:
        "The stick house was chosen for its balance of simplicity and strength.",
    text_ko: "나뭇가지 집은 단순함과 강함의 균형을 이루기 위해 선택되었어요.",
    updatedAt: Timestamp.now(),
  ),
  StoryScript(
    id: "${dummyStoryThreeLittlePigs.title}_7",
    storyId: dummyStoryThreeLittlePigs.title,
    index: 7,
    role: "story_teller",
    text_en: "The brick house represented durability and safety.",
    text_ko: "벽돌 집은 내구성과 안전함을 상징했어요.",
    updatedAt: Timestamp.now(),
  ),
  StoryScript(
    id: "${dummyStoryThreeLittlePigs.title}_8",
    storyId: dummyStoryThreeLittlePigs.title,
    index: 8,
    role: "me",
    text_en: "What were the advantages of each material?",
    text_ko: "각 재료의 장점은 무엇이었을까요?",
    updatedAt: Timestamp.now(),
  ),
  // Cycle 3 (scripts 9-12)
  StoryScript(
    id: "${dummyStoryThreeLittlePigs.title}_9",
    storyId: dummyStoryThreeLittlePigs.title,
    index: 9,
    role: "story_teller",
    text_en: "A big bad wolf was lurking in the nearby forest.",
    text_ko: "근처 숲 속에는 무서운 큰 늑대가 숨어 있었어요.",
    updatedAt: Timestamp.now(),
  ),
  StoryScript(
    id: "${dummyStoryThreeLittlePigs.title}_10",
    storyId: dummyStoryThreeLittlePigs.title,
    index: 10,
    role: "story_teller",
    text_en: "He had heard about the pigs and their plans.",
    text_ko: "늑대는 아기돼지들의 계획을 들었어요.",
    updatedAt: Timestamp.now(),
  ),
  StoryScript(
    id: "${dummyStoryThreeLittlePigs.title}_11",
    storyId: dummyStoryThreeLittlePigs.title,
    index: 11,
    role: "story_teller",
    text_en: "His hunger drove him to seek an easy meal.",
    text_ko: "그의 배고픔은 그에게 쉽게 먹을 수 있는 먹잇감을 찾아 나서게 했어요.",
    updatedAt: Timestamp.now(),
  ),
  StoryScript(
    id: "${dummyStoryThreeLittlePigs.title}_12",
    storyId: dummyStoryThreeLittlePigs.title,
    index: 12,
    role: "me",
    text_en: "Why was the wolf so interested in the little pigs?",
    text_ko: "늑대는 왜 아기돼지들에게 그렇게 관심이 많았을까요?",
    updatedAt: Timestamp.now(),
  ),
  // Cycle 4 (scripts 13-16)
  StoryScript(
    id: "${dummyStoryThreeLittlePigs.title}_13",
    storyId: dummyStoryThreeLittlePigs.title,
    index: 13,
    role: "story_teller",
    text_en: "The wolf first approached the straw house.",
    text_ko: "늑대는 먼저 짚 집에 다가갔어요.",
    updatedAt: Timestamp.now(),
  ),
  StoryScript(
    id: "${dummyStoryThreeLittlePigs.title}_14",
    storyId: dummyStoryThreeLittlePigs.title,
    index: 14,
    role: "story_teller",
    text_en: "He knocked on the door with a sly grin.",
    text_ko: "그는 교활한 미소와 함께 문을 두드렸어요.",
    updatedAt: Timestamp.now(),
  ),
  StoryScript(
    id: "${dummyStoryThreeLittlePigs.title}_15",
    storyId: dummyStoryThreeLittlePigs.title,
    index: 15,
    role: "story_teller",
    text_en: "The pig inside trembled with fear.",
    text_ko: "집 안의 돼지는 두려움에 떨었어요.",
    updatedAt: Timestamp.now(),
  ),
  StoryScript(
    id: "${dummyStoryThreeLittlePigs.title}_16",
    storyId: dummyStoryThreeLittlePigs.title,
    index: 16,
    role: "me",
    text_en: "How did the pig react to the wolf's arrival?",
    text_ko: "돼지는 늑대의 도착에 어떻게 반응했을까요?",
    updatedAt: Timestamp.now(),
  ),
  // Cycle 5 (scripts 17-20)
  StoryScript(
    id: "${dummyStoryThreeLittlePigs.title}_17",
    storyId: dummyStoryThreeLittlePigs.title,
    index: 17,
    role: "story_teller",
    text_en: "With a huff and a puff, the wolf blew the straw house away.",
    text_ko: "늑대는 한숨을 쉬며 짚 집을 날려버렸어요.",
    updatedAt: Timestamp.now(),
  ),
  StoryScript(
    id: "${dummyStoryThreeLittlePigs.title}_18",
    storyId: dummyStoryThreeLittlePigs.title,
    index: 18,
    role: "story_teller",
    text_en: "The fragile house collapsed in an instant.",
    text_ko: "그 연약한 집은 순식간에 무너져 내렸어요.",
    updatedAt: Timestamp.now(),
  ),
  StoryScript(
    id: "${dummyStoryThreeLittlePigs.title}_19",
    storyId: dummyStoryThreeLittlePigs.title,
    index: 19,
    role: "story_teller",
    text_en: "The pig ran out just in time to escape.",
    text_ko: "돼지는 아슬아슬하게 도망쳐 나갔어요.",
    updatedAt: Timestamp.now(),
  ),
  StoryScript(
    id: "${dummyStoryThreeLittlePigs.title}_20",
    storyId: dummyStoryThreeLittlePigs.title,
    index: 20,
    role: "me",
    text_en: "What was the pig's plan after escaping the straw house?",
    text_ko: "돼지는 짚 집을 탈출한 후 어떤 계획을 세웠을까요?",
    updatedAt: Timestamp.now(),
  ),
  // Cycle 6 (scripts 21-24)
  StoryScript(
    id: "${dummyStoryThreeLittlePigs.title}_21",
    storyId: dummyStoryThreeLittlePigs.title,
    index: 21,
    role: "story_teller",
    text_en: "The frightened pig dashed to the stick house of his sibling.",
    text_ko: "겁에 질린 돼지는 형제의 나뭇가지 집으로 달려갔어요.",
    updatedAt: Timestamp.now(),
  ),
  StoryScript(
    id: "${dummyStoryThreeLittlePigs.title}_22",
    storyId: dummyStoryThreeLittlePigs.title,
    index: 22,
    role: "story_teller",
    text_en: "The stick house offered more shelter than the straw house.",
    text_ko: "나뭇가지 집은 짚 집보다 더 나은 보호를 제공했어요.",
    updatedAt: Timestamp.now(),
  ),
  StoryScript(
    id: "${dummyStoryThreeLittlePigs.title}_23",
    storyId: dummyStoryThreeLittlePigs.title,
    index: 23,
    role: "story_teller",
    text_en: "Yet, anxiety still filled the air as the wolf approached.",
    text_ko: "그러나 늑대가 다가오자 불안감이 감돌았어요.",
    updatedAt: Timestamp.now(),
  ),
  StoryScript(
    id: "${dummyStoryThreeLittlePigs.title}_24",
    storyId: dummyStoryThreeLittlePigs.title,
    index: 24,
    role: "me",
    text_en: "How did the pigs plan to defend their new home?",
    text_ko: "돼지들은 새로운 집을 어떻게 방어할 계획이었을까요?",
    updatedAt: Timestamp.now(),
  ),
  // Cycle 7 (scripts 25-28)
  StoryScript(
    id: "${dummyStoryThreeLittlePigs.title}_25",
    storyId: dummyStoryThreeLittlePigs.title,
    index: 25,
    role: "story_teller",
    text_en: "The wolf, undeterred, attacked the stick house.",
    text_ko: "늑대는 포기하지 않고 나뭇가지 집을 공격했어요.",
    updatedAt: Timestamp.now(),
  ),
  StoryScript(
    id: "${dummyStoryThreeLittlePigs.title}_26",
    storyId: dummyStoryThreeLittlePigs.title,
    index: 26,
    role: "story_teller",
    text_en: "He huffed and puffed with all his might.",
    text_ko: "그는 모든 힘을 다해 숨을 내쉬며 불었어요.",
    updatedAt: Timestamp.now(),
  ),
  StoryScript(
    id: "${dummyStoryThreeLittlePigs.title}_27",
    storyId: dummyStoryThreeLittlePigs.title,
    index: 27,
    role: "story_teller",
    text_en: "The flimsy structure couldn’t hold up against the force.",
    text_ko: "연약한 구조는 그 힘을 버티지 못했어요.",
    updatedAt: Timestamp.now(),
  ),
  StoryScript(
    id: "${dummyStoryThreeLittlePigs.title}_28",
    storyId: dummyStoryThreeLittlePigs.title,
    index: 28,
    role: "me",
    text_en: "What did the pigs do after the stick house fell?",
    text_ko: "나뭇가지 집이 무너진 후 돼지들은 어떻게 했을까요?",
    updatedAt: Timestamp.now(),
  ),
  // Cycle 8 (scripts 29-32)
  StoryScript(
    id: "${dummyStoryThreeLittlePigs.title}_29",
    storyId: dummyStoryThreeLittlePigs.title,
    index: 29,
    role: "story_teller",
    text_en:
        "Both pigs hurried to the strong brick house of their other sibling.",
    text_ko: "두 돼지는 다른 형제의 튼튼한 벽돌 집으로 서둘러 갔어요.",
    updatedAt: Timestamp.now(),
  ),
  StoryScript(
    id: "${dummyStoryThreeLittlePigs.title}_30",
    storyId: dummyStoryThreeLittlePigs.title,
    index: 30,
    role: "story_teller",
    text_en: "The brick house stood firm and unyielding.",
    text_ko: "벽돌 집은 단단하고 굳건하게 서 있었어요.",
    updatedAt: Timestamp.now(),
  ),
  StoryScript(
    id: "${dummyStoryThreeLittlePigs.title}_31",
    storyId: dummyStoryThreeLittlePigs.title,
    index: 31,
    role: "story_teller",
    text_en: "It was built to withstand any storm, or wolf’s breath.",
    text_ko: "그 집은 어떤 폭풍이나 늑대의 숨결도 견딜 수 있도록 지어졌어요.",
    updatedAt: Timestamp.now(),
  ),
  StoryScript(
    id: "${dummyStoryThreeLittlePigs.title}_32",
    storyId: dummyStoryThreeLittlePigs.title,
    index: 32,
    role: "me",
    text_en: "How did the brick house differ from the others?",
    text_ko: "벽돌 집은 다른 집들과 어떻게 달랐을까요?",
    updatedAt: Timestamp.now(),
  ),
  // Cycle 9 (scripts 33-36)
  StoryScript(
    id: "${dummyStoryThreeLittlePigs.title}_33",
    storyId: dummyStoryThreeLittlePigs.title,
    index: 33,
    role: "story_teller",
    text_en: "The wolf arrived at the brick house with a menacing glare.",
    text_ko: "늑대는 위협적인 눈빛과 함께 벽돌 집에 도착했어요.",
    updatedAt: Timestamp.now(),
  ),
  StoryScript(
    id: "${dummyStoryThreeLittlePigs.title}_34",
    storyId: dummyStoryThreeLittlePigs.title,
    index: 34,
    role: "story_teller",
    text_en: "He blew with all his might, but the house stood strong.",
    text_ko: "그는 온 힘을 다해 불었지만, 집은 굳건히 버텼어요.",
    updatedAt: Timestamp.now(),
  ),
  StoryScript(
    id: "${dummyStoryThreeLittlePigs.title}_35",
    storyId: dummyStoryThreeLittlePigs.title,
    index: 35,
    role: "story_teller",
    text_en: "His efforts only enraged him further.",
    text_ko: "그의 노력은 오히려 그를 더욱 화나게 했어요.",
    updatedAt: Timestamp.now(),
  ),
  StoryScript(
    id: "${dummyStoryThreeLittlePigs.title}_36",
    storyId: dummyStoryThreeLittlePigs.title,
    index: 36,
    role: "me",
    text_en: "What did the wolf do after his failed attempt?",
    text_ko: "실패한 후 늑대는 무엇을 했을까요?",
    updatedAt: Timestamp.now(),
  ),
  // Cycle 10 (scripts 37-40)
  StoryScript(
    id: "${dummyStoryThreeLittlePigs.title}_37",
    storyId: dummyStoryThreeLittlePigs.title,
    index: 37,
    role: "story_teller",
    text_en: "Determined, the wolf tried to enter through the chimney.",
    text_ko: "단호하게 늑대는 굴뚝을 통해 들어가려 했어요.",
    updatedAt: Timestamp.now(),
  ),
  StoryScript(
    id: "${dummyStoryThreeLittlePigs.title}_38",
    storyId: dummyStoryThreeLittlePigs.title,
    index: 38,
    role: "story_teller",
    text_en: "He climbed onto the roof, his eyes glinting with malice.",
    text_ko: "그는 지붕에 올라 교활한 눈빛을 보였어요.",
    updatedAt: Timestamp.now(),
  ),
  StoryScript(
    id: "${dummyStoryThreeLittlePigs.title}_39",
    storyId: dummyStoryThreeLittlePigs.title,
    index: 39,
    role: "story_teller",
    text_en: "The pigs watched anxiously from inside the house.",
    text_ko: "돼지들은 집 안에서 초조하게 지켜봤어요.",
    updatedAt: Timestamp.now(),
  ),
  StoryScript(
    id: "${dummyStoryThreeLittlePigs.title}_40",
    storyId: dummyStoryThreeLittlePigs.title,
    index: 40,
    role: "me",
    text_en: "How did the pigs prepare for the wolf’s next move?",
    text_ko: "돼지들은 늑대의 다음 행동에 어떻게 대비했을까요?",
    updatedAt: Timestamp.now(),
  ),
  // Cycle 11 (scripts 41-44)
  StoryScript(
    id: "${dummyStoryThreeLittlePigs.title}_41",
    storyId: dummyStoryThreeLittlePigs.title,
    index: 41,
    role: "story_teller",
    text_en: "Inside, the pigs quickly devised a clever plan.",
    text_ko: "집 안에서 돼지들은 빠르게 기발한 계획을 세웠어요.",
    updatedAt: Timestamp.now(),
  ),
  StoryScript(
    id: "${dummyStoryThreeLittlePigs.title}_42",
    storyId: dummyStoryThreeLittlePigs.title,
    index: 42,
    role: "story_teller",
    text_en: "They prepared a boiling pot of water under the chimney.",
    text_ko: "그들은 굴뚝 아래에 끓는 물을 준비했어요.",
    updatedAt: Timestamp.now(),
  ),
  StoryScript(
    id: "${dummyStoryThreeLittlePigs.title}_43",
    storyId: dummyStoryThreeLittlePigs.title,
    index: 43,
    role: "story_teller",
    text_en: "Their determination was as strong as the brick walls.",
    text_ko: "그들의 결의는 벽돌 집의 벽처럼 강했어요.",
    updatedAt: Timestamp.now(),
  ),
  StoryScript(
    id: "${dummyStoryThreeLittlePigs.title}_44",
    storyId: dummyStoryThreeLittlePigs.title,
    index: 44,
    role: "me",
    text_en: "What do you think was their strategy to stop the wolf?",
    text_ko: "늑대를 막기 위한 그들의 전략은 무엇이었을까요?",
    updatedAt: Timestamp.now(),
  ),
  // Cycle 12 (scripts 45-48)
  StoryScript(
    id: "${dummyStoryThreeLittlePigs.title}_45",
    storyId: dummyStoryThreeLittlePigs.title,
    index: 45,
    role: "story_teller",
    text_en: "The wolf, unaware of the trap, descended the chimney.",
    text_ko: "늑대는 함정의 존재를 모른 채 굴뚝을 타고 내려왔어요.",
    updatedAt: Timestamp.now(),
  ),
  StoryScript(
    id: "${dummyStoryThreeLittlePigs.title}_46",
    storyId: dummyStoryThreeLittlePigs.title,
    index: 46,
    role: "story_teller",
    text_en: "As he reached the bottom, he was met with boiling water.",
    text_ko: "그가 아래에 도착하자, 끓는 물이 그를 맞이했어요.",
    updatedAt: Timestamp.now(),
  ),
  StoryScript(
    id: "${dummyStoryThreeLittlePigs.title}_47",
    storyId: dummyStoryThreeLittlePigs.title,
    index: 47,
    role: "story_teller",
    text_en: "In agony, the wolf fled the brick house.",
    text_ko: "고통 속에 늑대는 벽돌 집에서 도망쳤어요.",
    updatedAt: Timestamp.now(),
  ),
  StoryScript(
    id: "${dummyStoryThreeLittlePigs.title}_48",
    storyId: dummyStoryThreeLittlePigs.title,
    index: 48,
    role: "me",
    text_en: "How did the pigs feel about their successful plan?",
    text_ko: "돼지들은 그들의 성공적인 계획에 대해 어떻게 느꼈을까요?",
    updatedAt: Timestamp.now(),
  ),
  // Final Cycle (scripts 49-51)
  StoryScript(
    id: "${dummyStoryThreeLittlePigs.title}_49",
    storyId: dummyStoryThreeLittlePigs.title,
    index: 49,
    role: "story_teller",
    text_en: "Safe and sound, all three pigs celebrated their unity.",
    text_ko: "안전하게, 세 아기돼지는 그들의 단합을 축하했어요.",
    updatedAt: Timestamp.now(),
  ),
  StoryScript(
    id: "${dummyStoryThreeLittlePigs.title}_50",
    storyId: dummyStoryThreeLittlePigs.title,
    index: 50,
    role: "story_teller",
    text_en: "They learned that hard work and smart choices win in the end.",
    text_ko: "그들은 결국 노력과 현명한 선택이 승리한다는 것을 배웠어요.",
    updatedAt: Timestamp.now(),
  ),
  StoryScript(
    id: "${dummyStoryThreeLittlePigs.title}_51",
    storyId: dummyStoryThreeLittlePigs.title,
    index: 51,
    role: "story_teller",
    text_en:
        "Their tale of resilience and cooperation became a timeless legend.",
    text_ko: "그들의 회복력과 협력의 이야기는 영원한 전설이 되었답니다.",
    updatedAt: Timestamp.now(),
  ),
];
