default_platform(:android)

platform :android do
  desc "Deploy a new version to the Google Play"
  lane :deploy do
    sh "flutter build appbundle"
    upload_to_play_store(
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      track: "production",
      skip_upload_metadata: false,
      skip_upload_images: true,
      skip_upload_changelogs: false,
      skip_upload_screenshots: true,
    )
  end
end